import { ArrowDown, CheckCircle2, PiggyBank, TrendingDown, Wallet } from 'lucide-react';
import RiskScore from './RiskScore';
import { riskStatus } from '../utils/risk';
import { formatINR } from '../utils/format';

function Label({ children }) {
  return <p className="text-[10px] font-semibold uppercase tracking-wider text-faint">{children}</p>;
}

/**
 * Before/after risk visualization for the optimizer result.
 * Pure presentational — receives the engine's computed result object.
 */
export default function BeforeAfterRisk({ result, selectedOptions = [] }) {
  const before = riskStatus(result.beforeRisk);
  const after = riskStatus(result.afterRisk);

  return (
    <div className="space-y-5">
      <div className="flex flex-col items-center gap-4 rounded-xl border border-line bg-panel2/50 p-5 sm:flex-row sm:justify-around">
        <div className="flex flex-col items-center">
          <RiskScore score={result.beforeRisk} size={128} caption="Before optimization" />
        </div>
        <div className="flex h-10 w-10 items-center justify-center rounded-full border border-line bg-panel">
          <ArrowDown className="h-5 w-5 text-success" />
        </div>
        <div className="flex flex-col items-center">
          <RiskScore score={result.afterRisk} size={128} caption="After optimization" />
        </div>
      </div>

      <div className="flex items-center justify-between rounded-xl border border-success/25 bg-success/[0.07] px-4 py-3">
        <div className="flex items-center gap-2.5">
          <TrendingDown className="h-5 w-5 text-success" />
          <div>
            <p className="text-sm font-bold text-white">{result.reduction}-point risk reduction</p>
            <p className="text-[11px] text-muted">
              {before.label} → <span className="font-semibold" style={{ color: after.hex }}>{after.label}</span> · projected by the optimization engine
            </p>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-3 gap-3">
        <div className="rounded-lg border border-line bg-panel2/60 p-3">
          <div className="flex items-center gap-1.5">
            <Wallet className="h-3.5 w-3.5 text-accent" />
            <Label>Budget Used</Label>
          </div>
          <p className="mt-1 text-base font-bold text-white">{formatINR(result.budgetUsed)}</p>
        </div>
        <div className="rounded-lg border border-line bg-panel2/60 p-3">
          <div className="flex items-center gap-1.5">
            <PiggyBank className="h-3.5 w-3.5 text-success" />
            <Label>Remaining</Label>
          </div>
          <p className="mt-1 text-base font-bold text-white">{formatINR(result.budgetRemaining)}</p>
        </div>
        <div className="rounded-lg border border-line bg-panel2/60 p-3">
          <Label>Utilization</Label>
          <p className="mt-1 text-base font-bold text-white">{result.utilizationPct}%</p>
          <div className="mt-1.5 h-1 overflow-hidden rounded-full bg-line">
            <div className="h-full rounded-full bg-accent" style={{ width: `${result.utilizationPct}%` }} />
          </div>
        </div>
      </div>

      {selectedOptions.length > 0 && (
        <div>
          <Label>Investments selected by engine</Label>
          <ul className="mt-2 space-y-1.5">
            {selectedOptions.map((o) => (
              <li
                key={o.id}
                className="flex items-center justify-between rounded-lg border border-line/70 bg-panel2/40 px-3 py-2 text-xs"
              >
                <span className="flex items-center gap-2 font-medium text-ink">
                  <CheckCircle2 className="h-3.5 w-3.5 text-success" /> {o.name}
                </span>
                <span className="font-mono text-muted">
                  {formatINR(o.cost)} · −{o.riskReduction} pts
                </span>
              </li>
            ))}
          </ul>
          <p className="mt-2 text-[11px] leading-relaxed text-faint">
            Projections are generated by the mock optimization engine in the service layer. The backend team will replace it
            with the real engine via POST /api/optimizer/calculate — this panel needs no changes.
          </p>
        </div>
      )}
    </div>
  );
}
